### ISSUE TITLE
Describe the import of style.css in README.md

### ISSUE THREAD

**Issue by nwtgck** [tachibana-shin/vue-console-feed#3]
Fantastic work!
Thank you so much for creating this! I'm going to use vue-console-feed.

I think it is better to add the following import in README.md. Without it, the style is gone. It took some time to figure out how to do.

```ts
import "vue-console-feed/style.css"
```

**Comment by tachibana-shin** [comment]
> Fantastic work! Thank you so much for creating this! I'm going to use vue-console-feed.
> 
> I think it is better to add the following import in README.md. Without it, the style is gone. It took some time to figure out how to do.
> 
> ```ts
> import "vue-console-feed/style.css"
> ```

thank you i will update the readme now

**Comment by nwtgck** [comment]
Thanks. I confirmed the change.
